### ISSUE TITLE
Does it work well now

### ISSUE THREAD

**Issue by wowoName** [kohlschutter/jacline#1]
Does it work well now

**Comment by kohlschuetter** [comment]
What are you waiting for

**Comment by wowoName** [comment]
see https://github.com/Vertispan/j2clmavenplugin/issues/262#issuecomment-2084316510

**Comment by kohlschuetter** [comment]
I'm not sure I understand what you're looking for, @wowoName.

I think you want to transpile some Java code and then access it from the JavaScript console, is that right?

If that's the case, jacline makes it very easy to do that:

All you need is to annotate the class with `@JsType` and `@JsExport`, and also annotate the method in question with `@JsExport`. Then your class will be accessible from vanilla JavaScript and the console by specifying the full package name (e.g., `com.example.YourClass`), and the methods (static or not) will be accessible by its Java name.
